#!/bin/sh
#
# This is part 2 of the ppp-on script. It will perform the connection
# protocol for the desired connection.
#
#!/bin/sh
#!/bin/sh

chat -v -s -r /var/report \
        TIMEOUT         100             \
        ''              ate0            \
        OK              at              \
        OK              ''              \
        ''              ATD$TELEPHONE   \
        CONNECT
