#!/bin/sh

INSTALL="/srv/webtest/"
DESC=webtest
BIN_PATH=/srv/webtest/bin
ARGS=
NAME=${BIN_PATH}/${DESC}

ret=1

if [ -f "/sys/class/gpio/gpio60/value" ];then
	ret=`cat /sys/class/gpio/gpio60/value`
	ifconfig eth0 192.168.1.165
	ifconfig eth1 192.168.2.165
fi

do_service() {
	if [ ! -f "/etc/functest.res" ];then
		if [ -d "$INSTALL" ];then
			cd $INSTALL/bin
			if [[ $ret -eq 0 ]];then
				./webtest -f &
			fi
           return 
       fi
    fi
    #launch stable-test
    if [ -f "/etc/stable.todo" ];then
        STABLEIP=`cat /etc/stable.todo | awk '{print $1}'`
        if [ -d "$INSTALL" ];then
            ifconfig eth0 $STABLEIP
            cd $INSTALL/bin
			if [[ $ret -eq 0 ]];then
				./webtest -s &
			fi
            return
        fi
    fi
}

start() {
     echo -n "Starting ${DESC}: "
     do_service
     echo "OK"
}

stop() {
    echo -n "Stopping ${DESC}: "
    killall ${DESC}
}

restart() {
    stop
    start
}

case "$1" in
  start)
    start
	;;
  stop)
    stop
	;;
  restart|force-reload)
    restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
