#!/bin/sh
#-rtdate -w

#-if [[ -f "/sys/class/gpio/gpio60/value" ]];then
#-    rtdate -s 1970.1.1-0.0.0
#-    rtdate -w
#-fi

#-开始用户应用程序脚本
nohup /usr/bin/iot_monitor > /opt/share/iot/nohup.out 2>&1 &
